Use the hardware dongle for signing
Contributes to CURA-11482

diff --git a/.github/workflows/cura-installer-windows.yml b/.github/workflows/cura-installer-windows.yml
--- a/.github/workflows/cura-installer-windows.yml
+++ b/.github/workflows/cura-installer-windows.yml
@@ -148,7 +148,9 @@ jobs:
 
       - name: Sign the Windows msi installer (Powershell)
         run: |
-          & "C:/Program Files (x86)/Windows Kits/10/bin/10.0.17763.0/x86/signtool.exe" sign /f $Env:PFX_PATH /p "$Env:WIN_CERT_INSTALLER_CER_PASS" /fd SHA256 /t http://timestamp.digicert.com "${{steps.filename.outputs.INSTALLER_FILENAME }}.msi" || echo "::warning title=Signing installer failed!::The `msi` couldn't be signed."
+          [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("${{ secrets.WIN_CERT_INSTALLER_CER }}")) > code_sign.cer
+          & signtool sign /v /fd sha256 /tr http://timestamp.digicert.com /td sha256 /f code_sign.cer /csp "eToken Base Cryptographic Provider" /kc ${{ secret.WIN_TOKEN_CONTAINER }} "${{steps.filename.outputs.INSTALLER_FILENAME }}.msi" || echo "::error title=Signing installer failed!::The msi couldn't be signed."
+          del code_sign.cer
         working-directory: dist
 
       - name: Create the Windows exe installer (Powershell)
@@ -160,7 +162,9 @@ jobs:
       - name: Sign the Windows exe installer (Powershell)
         if: ${{ always() }}
         run: |
-          & "C:/Program Files (x86)/Windows Kits/10/bin/10.0.17763.0/x86/signtool.exe" sign /f $Env:PFX_PATH /p "$Env:WIN_CERT_INSTALLER_CER_PASS" /fd SHA256 /t http://timestamp.digicert.com "${{steps.filename.outputs.INSTALLER_FILENAME }}.exe" || echo "::warning title=Signing installer failed!::The `exe` couldn't be signed."
+          [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("${{ secrets.WIN_CERT_INSTALLER_CER }}")) > code_sign.cer
+          & signtool sign /v /fd sha256 /tr http://timestamp.digicert.com /td sha256 /f code_sign.cer /csp "eToken Base Cryptographic Provider" /kc ${{ secret.WIN_TOKEN_CONTAINER }} "${{steps.filename.outputs.INSTALLER_FILENAME }}.exe" || echo "::error title=Signing installer failed!::The exe couldn't be signed."
+          del code_sign.cer
         working-directory: dist
 
       - name: Remove internal packages before uploading
