add missing `s`
Contributes to CURA-11482

diff --git a/.github/workflows/cura-installer-windows.yml b/.github/workflows/cura-installer-windows.yml
--- a/.github/workflows/cura-installer-windows.yml
+++ b/.github/workflows/cura-installer-windows.yml
@@ -149,7 +149,7 @@ jobs:
       - name: Sign the Windows msi installer (Powershell)
         run: |
           [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("${{ secrets.WIN_CERT_INSTALLER_CER }}")) > code_sign.cer
-          & signtool sign /v /fd sha256 /tr http://timestamp.digicert.com /td sha256 /f code_sign.cer /csp "eToken Base Cryptographic Provider" /kc ${{ secret.WIN_TOKEN_CONTAINER }} "${{steps.filename.outputs.INSTALLER_FILENAME }}.msi" || echo "::error title=Signing installer failed!::The msi couldn't be signed."
+          & signtool sign /v /fd sha256 /tr http://timestamp.digicert.com /td sha256 /f code_sign.cer /csp "eToken Base Cryptographic Provider" /kc ${{ secrets.WIN_TOKEN_CONTAINER }} "${{steps.filename.outputs.INSTALLER_FILENAME }}.msi" || echo "::error title=Signing installer failed!::The msi couldn't be signed."
           del code_sign.cer
         working-directory: dist
 
@@ -163,7 +163,7 @@ jobs:
         if: ${{ always() }}
         run: |
           [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("${{ secrets.WIN_CERT_INSTALLER_CER }}")) > code_sign.cer
-          & signtool sign /v /fd sha256 /tr http://timestamp.digicert.com /td sha256 /f code_sign.cer /csp "eToken Base Cryptographic Provider" /kc ${{ secret.WIN_TOKEN_CONTAINER }} "${{steps.filename.outputs.INSTALLER_FILENAME }}.exe" || echo "::error title=Signing installer failed!::The exe couldn't be signed."
+          & signtool sign /v /fd sha256 /tr http://timestamp.digicert.com /td sha256 /f code_sign.cer /csp "eToken Base Cryptographic Provider" /kc ${{ secrets.WIN_TOKEN_CONTAINER }} "${{steps.filename.outputs.INSTALLER_FILENAME }}.exe" || echo "::error title=Signing installer failed!::The exe couldn't be signed."
           del code_sign.cer
         working-directory: dist
 
