Use conan user and pass for jfrog remote
Fixes CURA-11528

diff --git a/.github/workflows/cura-installer-windows.yml b/.github/workflows/cura-installer-windows.yml
--- a/.github/workflows/cura-installer-windows.yml
+++ b/.github/workflows/cura-installer-windows.yml
@@ -98,9 +98,14 @@ jobs:
           conan config install https://github.com/Ultimaker/conan-config.git
           conan config install https://github.com/Ultimaker/conan-config.git -a "-b runner/${{ runner.os }}/${{ runner.arch }}"
 
+      - name: Add runner credentials to cura remote
+        run: conan user -p ${{ secrets.CONAN_PASS }} -r cura ${{ secrets.CONAN_USER }}
+
       - name: Add Cura private Artifactory remote
         if: ${{ inputs.conan_internal }}
-        run: conan config install https://github.com/Ultimaker/conan-config.git -a "-b runner/internal"
+        run: |
+          conan config install https://github.com/Ultimaker/conan-config.git -a "-b runner/internal"
+          conan user -p ${{ secrets.CONAN_PASS }} -r cura-private ${{ secrets.CONAN_USER }}
 
       - name: Create the Packages (Powershell)
         run: conan install $Env:CURA_CONAN_VERSION ${{ inputs.conan_args }} --build=missing --update -if cura_inst -g VirtualPythonEnv -o cura:enterprise="$Env:ENTERPRISE" -o cura:staging="$Env:STAGING" -o cura:internal=${{ inputs.conan_internal }} -c tools.build:skip_test=True -s curaengine:build_type=RelWithDebInfo
@@ -164,11 +169,7 @@ jobs:
         env:
           PFX_PATH: ${{ steps.create-pfx.outputs.PFX_PATH }}
         run: |
-          try {
-            & "C:/Program Files (x86)/Windows Kits/10/bin/10.0.17763.0/x86/signtool.exe" sign /f $Env:PFX_PATH /p "$Env:WIN_CERT_INSTALLER_CER_PASS" /fd SHA256 /t http://timestamp.digicert.com "${{steps.filename.outputs.INSTALLER_FILENAME }}.msi"
-          } catch {
-            echo "::warning title=Signing installer failed!::The `msi` couldn't be signed."
-          }
+          & "C:/Program Files (x86)/Windows Kits/10/bin/10.0.17763.0/x86/signtool.exe" sign /f $Env:PFX_PATH /p "$Env:WIN_CERT_INSTALLER_CER_PASS" /fd SHA256 /t http://timestamp.digicert.com "${{steps.filename.outputs.INSTALLER_FILENAME }}.msi" || echo "::warning title=Signing installer failed!::The `msi` couldn't be signed."
         working-directory: dist
 
       - name: Create the Windows exe installer (Powershell)
@@ -182,11 +183,7 @@ jobs:
         env:
           PFX_PATH: ${{ steps.create-pfx.outputs.PFX_PATH }}
         run: |
-          try {
-            & "C:/Program Files (x86)/Windows Kits/10/bin/10.0.17763.0/x86/signtool.exe" sign /f $Env:PFX_PATH /p "$Env:WIN_CERT_INSTALLER_CER_PASS" /fd SHA256 /t http://timestamp.digicert.com "${{steps.filename.outputs.INSTALLER_FILENAME }}.exe"
-          } catch {
-            echo "::warning title=Signing installer failed!::The `exe` couldn't be signed."
-          }
+          & "C:/Program Files (x86)/Windows Kits/10/bin/10.0.17763.0/x86/signtool.exe" sign /f $Env:PFX_PATH /p "$Env:WIN_CERT_INSTALLER_CER_PASS" /fd SHA256 /t http://timestamp.digicert.com "${{steps.filename.outputs.INSTALLER_FILENAME }}.exe" || echo "::warning title=Signing installer failed!::The `exe` couldn't be signed."
         working-directory: dist
 
       - name: Remove internal packages before uploading
